#! /bin/bash

#   Add service file to runlevel directory

/bin/cp /etc/init.d/debugfs-mount /etc/runlevels/default || true

#   Add service to runlevel

rc-update add debugfs-mount default

#   Update services list

rc-update -u
